services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: customer_postgres
    environment:
      - POSTGRES_USER=kassra
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer
    ports:
      - "6024:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kassra -d customer"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: customer_api
    command: uvicorn src.backend.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg://kassra:admin@postgres:5432/customer
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  mcp:
    build: .
    container_name: customer_mcp
    command: fastmcp run src/backend/api.py --transport http --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg://kassra:admin@postgres:5432/customer
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A src.backend.celery.celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - API_BASE_URL=http://api:8000
    env_file:
      - .env
    depends_on:
      - redis
      - api

volumes:
  redis_data:
  postgres_data:
